baseurl = "http://edwardmanning.com/"
theme = "blackburn"
languageCode = "en-us"
title = "Edward Manning"

[permalinks]
    post = "/:year/:month/:day/:slug/"

# Shown in the side menu
copyright = "&copy; 2016. All rights reserved."
canonifyurls = true
paginate = 10

[taxonomies]
  tag = "tags"
  topic = "categories"

[params]
  # Shown in the home page
  subtitle = "Relentless Improvement: The Pursuit of Mastery"
  brand = "Blog"
  # googleAnalytics = "Your Google Analytics tracking ID"
  # disqus = "Your Disqus shortname"
  # CSS name for highlight.js
  highlightjs = "androidstudio"
  dateFormat = "02 Jan 2006, 15:04"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 0
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 1
    identifier = "post"
    url = "/post/"

	